config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
  resources :projects do
    resources :sheets, only: %i(create show)
    resources :metrics, only: %i(index)
    resources :periods, only: %i(index)
  end
  resources :sheets, only: %i(edit update destroy) do
    resources :sections, only: %i(create)
    resources :entries, only: %i(update)
  end
  resources :sections, only: %i(show edit update destroy) do
    resources :rows, only: %i(new)
    resources :metrics, only: %i(new create) do
      resources :rows, only: %i(create)
    end
  end
  resources :rows, only: %i(show destroy)
  resources :metrics, only: %i(edit update) do
    resources :formulas, only: %i(create)
  end
  resources :formulas, only: %i(update destroy)
  patch "sheets/:id/sort", to: "sheets#sort"
  patch "sections/:id/sort", to: "sections#sort"
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  acts_as_list
  belongs_to :project
  has_many :sections, -> { order(position: :asc) }, dependent: :destroy
  has_many :rows, through: :sections
  after_create :auto_name
  # before_destroy :one_sheet_required

  private

  def auto_name
    update(name: "Sheet_#{id}")
  end

  def one_sheet_required
    Sheet.create(project: project) if project.sheets.count == 1
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: %i(show edit update destroy sort)
  before_action :set_project

  def show
    @periods = @project.periods
    @sections = @sheet.sections
    @metrics = Metric.joins(:rows).where(rows: { section_id: @sections.pluck(:id) }).distinct
    @entries = Entry.joins(:metric).where(metric: { metric_id: @metrics.pluck(:id) }).distinct
    # @project.cache_entries unless Entry.cached_hash
    # refresh_worksheet
    # raise
  end

  def create
    @sheet = Sheet.create(project: @project)
    redirect_to project_sheet_path(@project, @sheet)
  end

  def edit
    @project = @sheet.project
  end

  def update
    @sheet.update(sheet_params)
    redirect_to project_sheet_path(@project, @sheet)
  end

  def destroy
    @sheet.destroy
    redirect_to project_sheet_path(@project, @project.sheets.first)
  end

  def sort
    @sheet.insert_at(params[:position].to_i)
  end

  private

  def set_project
    @project = @sheet ? @sheet.project : Project.find(params[:project_id])
    @sheets = @project.sheets
  end

  def set_sheet
    @sheet = Sheet.find(params[:id])
  end

  def sheet_params
    params.require(:sheet).permit(:name)
  end

  def refresh_worksheet
    @output = {}
    @metrics.includes(:formula).each do |metric|
      @output[:"#{metric.id}"] = {}
      @periods.includes(:entries).each do |period|
        @output[:"#{metric.id}"][:"#{period.id}"] = {
          entry: period.entries.find_by(metric: metric),
          calc: metric.formula.process(period)
        }
      end
    end
    @output
  end
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_active_btn.html.erb
<div class="flex-middle bg-1l btn-sm gap-10" active>
  <%= link_to sheet.name, edit_sheet_path(sheet), class: "bg-1l fc-1n fw-5", data: {turbo_frame: "edit"} %>
  <%= button_to sheet_path(sheet), method: :delete, class: "fc-4n p-0 flex-middle", data: {turbo: false} do %>
    <span class="mso-icon pop-up">delete</span>
  <% end %>
</div>

app/views/sheets/_controls.html.erb
<div class="flex ai-center gap-10 mb-40">
  <div class="flex ai-center gap-10" data-controller="sortable" data-sortable-url-value="/sheets/:id/sort">
    <% @sheets.each do |sheet| %>
      <% if sheet == @sheet %>
        <%= turbo_frame_tag "edit", data: {id: sheet.id} do %>
          <%= render partial: "active_btn", locals: {sheet: sheet} %>
        <% end %>
      <% else %>
        <%= link_to sheet.name, project_sheet_path(@project, sheet), class: "btn-sm bg-2l bg-to-1l fc-2d fc-to-1n", data: {id: sheet.id, turbo: false} %>
      <% end %>
    <% end %>
  </div>
  <%= button_to project_sheets_path(@project), class: "round flex-middle bg-1n fc-white h-20px w-20px p-0 zoom-on-hover", data: {turbo: false} do %>
    <span class="mso-icon">add</span>
  <% end %>
</div>

app/views/sheets/_table.html.erb
<%= turbo_frame_tag "table" do %>
  <div data-controller="sections" data-src=<%= request.url %>>
      <%= turbo_frame_tag "sections", data: {controller: "sortable", sortable_url_value: "/sections/:id/sort", sortable_handle_value: true } do %>
        <% @sections.includes(:rows).each do |section| %>
          <%= render partial: "sections/default", locals: {section: section} %>
        <% end %>
      <% end %>
  </div>
<% end %>

app/views/sheets/edit.html.erb
<%= turbo_frame_tag "edit" do %>
  <%= simple_form_for(@sheet, data: {controller: "forms", action: "change->forms#submit"}, html: {class:"btn-sm-static bg-1l pos-rel outline-1n"}) do |f| %>
    <%= f.input_field :name, data: {forms_target: "input", action: "input->forms#resize"}, class: "fs-14 pl-5 pr-5 round-20" %>
    <%= link_to "×", :back, class: "fc-1n fw-6" %>
    <span class="block pos-abs op-0 fs-14 pl-5 pr-5" data-forms-target="resizer"><%= @sheet.name %></div>
  <% end %>
<% end %>

app/views/sheets/show.html.erb
<div class="bg-white round-20 w-100 p-20">
  <%= turbo_frame_tag "controls" do %>
    <%= render partial: "sheets/controls" %>
  <% end %>

  <div>
    <table class="mb-10 w-100 fixed-table">
      <thead>
        <td class="w-150px">
          <%= link_to project_periods_path(@project), class: "fs-12 fc-1n fw-5 flex ai-center" do %>
            <span class="mso-icon mr-5">calendar_month</span>
            Period settings
          <% end %>
        </td>
        <td class="text-center fs-12 fw-5">
          <div class=" bg-2l ml-5 mr-5 p-5">
            fixed
          </div>
        </td>
        <% @periods.each do |period| %>
          <td class="text-center fs-12 fw-5">
            <div class=" bg-2l ml-5 mr-5 p-5">
              <%= period.date&.strftime('%m-%Y') %>
            </div>
          </td>
        <% end %>
      </thead>
    </table>
  </div>

  <%= render partial: "sheets/table" %>

  <%= button_to sheet_sections_path(@sheet), class: "zoom-on-hover flex ai-center p-0" do %>
    <span class="mso-icon round flex-middle bg-1n fc-white h-20px w-20px p-0">add</span>
    <span class="fc-1n pl-5 fs-12 fw-5">Add section</span>
  <% end %>

  <%= turbo_frame_tag "results" %>

</div>