config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
  resources :projects do
    resources :sheets, only: %i(create show)
    resources :metrics, only: %i(index)
    resources :periods, only: %i(index)
  end
  resources :sheets, only: %i(edit update destroy) do
    resources :sections, only: %i(create)
    resources :entries, only: %i(update)
  end
  resources :sections, only: %i(show edit update destroy) do
    resources :rows, only: %i(new)
    resources :metrics, only: %i(new create) do
      resources :rows, only: %i(create)
    end
  end
  resources :rows, only: %i(show destroy)
  resources :metrics, only: %i(edit update) do
    resources :formulas, only: %i(create)
  end
  resources :formulas, only: %i(update destroy)
  patch "sheets/:id/sort", to: "sheets#sort"
  patch "sections/:id/sort", to: "sections#sort"
end

app/models/section.rb
class Section < ApplicationRecord
  acts_as_list
  belongs_to :sheet
  before_create :auto_name
  has_many :rows, -> { order(position: :asc) }, dependent: :destroy
  has_one :project, through: :sheet

  private

  def auto_name
    assign_attributes(name: "NewSection")
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i(show edit update destroy sort)
  before_action :set_constants, only: %i(show edit update)

  def create
    @sheet = Sheet.find(params[:sheet_id])
    @section = Section.create(sheet: @sheet)
    respond_to do |format|
      format.turbo_stream {render turbo_stream: (turbo_stream.append "sections", partial: "sections/default", locals: {section: @section})}
      format.html
    end
  end

  def show
    @sections = @sheet.sections
    @inactive_sections = @sections.where.not(id: @section.id)
  end

  def edit
  end

  def update
    @section.update(section_params)
    redirect_to project_sheet_path(@sheet.project, @sheet)
  end

  def destroy
    @sheet = @section.sheet
    @section.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: (turbo_stream.remove "section-#{@section.id}") }
      format.html { redirect_to project_sheet_path(@sheet.project, @sheet) }
    end
  end

  def sort
    @section.insert_at(params[:position].to_i)
  end

  private

  def set_section
    @section = Section.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:name)
  end

  def set_constants
    @sheet = @section.sheet
    @project = @sheet.project
    @periods = @project.periods
  end

end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_default.html.erb
<%= turbo_frame_tag "section-#{section.id}", data: {id: section.id}, class: "section" do %>
  <%= link_to section.name, section_path(section), data: {turbo_frame: "section-#{section.id}", action: "turbo:click->sections#update"}, class: "block pl-5 w-100 bg-2l fc-black fw-5 fs-14 border-t-2d border-b-2d" %>
  <%= render partial: "rows/list", locals: {section: section} %>
<% end %>

app/views/sections/edit.html.erb
<%= turbo_frame_tag "section-#{@section.id}" do %>
  <div class="bg-1l w-100 border-t-1n border-b-1n flex ai-center pl-5 pr-10 fs-14 pl-20" data-sections-target="active" action="turbo:click->sections#update" active>
    <%= simple_form_for(@section, data: {controller: "forms", action: "change->forms#submit "}) do |f| %>
      <%= f.input_field :name, data: {forms_target: "input", action: "input->forms#resize"}, class: "fw-6 fc-black fs-14 pl-5 pr-5 round-20" %>
      <%= link_to "×", section_path(@section), class: "fc-1n fw-6" %>
      <span class="block pos-abs op-0 fs-14 fw-6 pl-5 pr-5" data-forms-target="resizer"><%= @section.name %></div>
    <% end %>
  </div>
  <%= render partial: "rows/list", locals: {section: @section} %>
<% end %>

app/views/sections/show.html.erb
<%= turbo_frame_tag "section-#{@section.id}" do %>

  <div class="bg-1l w-100 flex ai-center pl-5 pr-10 fs-14 fc-1n border-b-1n border-t-1n" data-sections-target="active">
    <span class="mso-icon w-20px handle" data-sortable-target="handle">drag_indicator</span>
    <%= link_to @section.name, edit_section_path(@section), class:"fc-1n fw-6", data: {turbo_frame: "section-#{@section.id}"} %>
    <%= link_to section_path(@section), data: {turbo_method: :delete}, class: "fc-4n flex-middle w-20px" do %>
      <span class="mso-icon">delete</span>
    <% end %>
  </div>

  <%= render partial: "rows/list", locals: {section: @section} %>

  <%= link_to new_section_row_path(@section), data: {turbo_frame: "modal"}, class: "p-0 flex ai-center" do %>
    <span class="mso-icon round flex-middle bg-1n fc-white h-20px w-20px p-0">add</span>
    <span class="fc-1n pl-5 fs-12 fw-5">Add row</span>
  <% end %>

<% end %>