config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
  resources :projects do
    resources :sheets, only: %i(create show)
    resources :metrics, only: %i(index)
    resources :periods, only: %i(index)
  end
  resources :sheets, only: %i(edit update destroy) do
    resources :sections, only: %i(create)
    resources :entries, only: %i(update)
  end
  resources :sections, only: %i(show edit update destroy) do
    resources :rows, only: %i(new)
    resources :metrics, only: %i(new create) do
      resources :rows, only: %i(create)
    end
  end
  resources :rows, only: %i(show destroy)
  resources :metrics, only: %i(edit update) do
    resources :formulas, only: %i(create)
  end
  resources :formulas, only: %i(update destroy)
  patch "sheets/:id/sort", to: "sheets#sort"
  patch "sections/:id/sort", to: "sections#sort"
end

app/models/row.rb
class Row < ApplicationRecord
  acts_as_list
  belongs_to :section
  belongs_to :metric
  has_many :entries, ->{order 'date ASC'}, through: :metric
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  layout "modal", only: %i(new create)
  before_action :set_row, only: %i(show destroy)
  before_action :set_section

  def new
    @row = Row.new(section: @section)
    @sheet = @section.sheet
    @project = @sheet.project
    @metrics = @project.metrics
    @metrics = @metrics.search_by_name(params[:query]) if params[:query] && !params[:query].blank?
    @metrics = @metrics.first(5)
  end

  def create
    @metric = Metric.find(params[:metric_id])
    @sheet = @section.sheet
    @project = @sheet.project
    @row = Row.new(section: @section, metric: @metric)
    if @row.save
      redirect_to project_sheet_path(@project, @sheet)
    else
      render :new, status: 422
    end
  end

  def show
    @sheet = @section.sheet
    @inactive_rows = @sheet.rows.where.not(id: @row.id)
    @inactive_sections = @sheet.sections.where.not(id: @section.id)
  end

  def destroy
    @row.destroy
    @sheet = @section.sheet
    respond_to do |format|
      format.turbo_stream { render turbo_stream: (turbo_stream.remove "row-#{@row.id}") }
      format.html { redirect_to project_sheet_path(@sheet.project, @sheet) }
    end
  end

  private

  def set_row
    @row = Row.find(params[:id])
  end

  def set_section
    @section = params[:section_id] ? Section.find(params[:section_id]) : @row.section
  end
end

app/helpers/rows_helper.rb
module RowsHelper
end

app/views/rows/_default.html.erb
<tr>
  <td class="fs-12 nowrap w-150px">
    <%= turbo_frame_tag "row-#{row.id}" do %>
      <%= link_to row.metric.name, row_path(row), data: {turbo_frame: "row-#{row.id}", action: "turbo:click->sections#update", section: row.section.id}, class: "block pl-20 pr-10 pt-5 pb-5 fc-black" %>
    <% end %>
  </td>

  <% unless row.metric.fixed %>
    <td></td>
  <% end %>

  <% row.entries.each do |entry| %>
    <td class="pos-rel">
      <span class="pos-abs bottom-0 fs-8"><%= entry.id %></span>
      <% if entry.calc && !entry.value %>
        <span class="fs-14 text-end w-100 block pl-10 pr-10 pt-5 pb-5">
          <%= entry.calc %>
        </span>
      <% else %>
        <%= simple_form_for([@sheet, entry]) do |f| %>
          <%= f.input_field :value, class: "border-2l w-100 pl-10 pr-10 pt-5 pb-5 text-end bg-1l fc-5n" %>
        <% end %>
      <% end %>
    </td>
    <%# <%= render partial: "entries/cell", locals: {period: period, metric: row.metric} %>
  <% end %>

  <% if row.metric.fixed %>
    <% @periods.count.times do %>
      <td></td>
    <% end %>
  <% end %>
</tr>

app/views/rows/_list.html.erb
<table class="mb-10 w-100 fixed-table">
  <% section.rows.includes(metric: :formula).each do |row| %>
    <%= render partial: "rows/default", locals: {row: row} %>
  <% end %>
</table>

app/views/rows/new.html.erb
<% @title = "New row" %>

<div class="flex ai-center jc-between gap-10 mb-20 min-w-300">
  <%= link_to "Select metric", "", class: "btn-sm bg-1l fc-1n fw-5 w-100 text-center", data: {turbo_frame: "modal"} %>
  <%= link_to "Create new", new_section_metric_path(@section), class: "btn-sm bg-2l bg-to-1l fc-2d fc-to-1n w-100 text-center", data: {turbo_frame: "modal"} %>
</div>

<% if @project.metrics.empty? %>
  <p class="fs-12">No metric has been defined yet for this project</p>
<% else %>
  <%= form_tag new_section_row_path(@section), method: :get, data: {controller: "forms", turbo_frame: "metrics"} do %>
    <%= text_field_tag :query, "", data: {action: "input->forms#submit"}, class: "w-100 bg-1l fc-1n p-10", placeholder: "Search..." %>
  <% end %>
  <%= turbo_frame_tag "metrics" do %>
    <% if @metrics.empty? %>
      <p class="fs-12">No match for this project</p>
    <% else %>
      <% @metrics.each do |metric| %>
        <%= button_to metric.name, section_metric_rows_path(@section, metric), form: {data: { action: "turbo:submit-end->modals#redirect" }} %>
      <% end %>
    <% end %>
    <div class="w-100 border-b-2n p-10 mb-10"></div>
    <%= link_to "Manage project metrics", project_metrics_path(@project), class: "fs-12 fw-5 fc-1n", data: {turbo: false} %>
  <% end %>
<% end %>

app/views/rows/show.html.erb
<%= turbo_frame_tag "row-#{@row.id}" do %>
  <div class="flex ai-center gap-20 pl-20 pr-10 pt-5 pb-5 bg-1l fc-1n" data-sections-target="active">
    <%= link_to @row.metric.name, edit_metric_path(@row.metric), data: {turbo_frame: "modal"}, class: "fw-6" %>
    <%= link_to row_path(@row), data: {turbo_method: :delete}, class: "flex-middle" do  %>
      <span class="mso-icon fc-4n">delete</span>
    <% end %>
  </div>
<% end %>